[27기 오동녘어진이] theme 파일에 mixin 추가
wecode-bootcamp-korea/27-2nd-SUULGO-frontend pull request #1
Opened 2021-12-14 05:56 UTC by eojine94

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- theme 파일에 mixin 코드 추가

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. theme 파일에 mixin 코드 추가

<br />

## :: 성장 포인트
- style component 에서 mixin 사용 방법을 공부함.

<br />

## :: 기타 질문 및 특이 사항
-

2021-12-14 08:31 UTC, younuk23 requested changes
리뷰 확인해주세요 어진님!

그리고 PR 본문에 양식 깨져있는 것 있는데 항상 꼼꼼히 확인해주세요

2021-12-14 08:31 UTC, younuk23 commented on src/styles/theme.js
> +  flexStart: 'display: flex, justify-content: flex-start;',
단순한 string보다
```js
flexStart: css`
   display:flex;
   justify-content: flex-start;
`
```
이런 식으로 styledComponents의 css 활용하는것을 권장드립니다!!

그리고 start, center, centerColumn 이렇게 다 분리해두는 것 보단 하나의 flexSet 함수로 만드는 건 어떨까요??
한번 시도해보시고 막히시면 질문 주세요!

2021-12-14 09:36 UTC, eojine94 commented on src/styles/theme.js
> +  flexStart: 'display: flex, justify-content: flex-start;',
수정완료했습니다 ~!

2021-12-15 05:01 UTC, younuk23 approved these changes
LGTM 👍

2021-12-15 05:01 UTC, merged