[27기 구유진] Add: survey 일부기능구현
wecode-bootcamp-korea/27-2nd-SUULGO-frontend pull request #12
Opened 2021-12-20 14:41 UTC by sodalite1204

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 상수데이터를 이용하여 설문조사 폼을 구현하여 API POST통신
<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. survey폼 구현 (각 값당 state로 관리)
    - 단수 답변 : input 라디오 버튼 사용 >> 객체로 담아서 처리
    - 복수 답변 : input checkbox 사용 >> 복수 답변값은 배열로 담아서 처리
    - 옵션 답변 : react-select 라이브러리 사용으로 구현 >> 객체로 담아서 처리
    - 자유형식 답변 : input text로 구현 
2. 다음 버튼 클릭시 설문조사 내용이 바뀌게 구현
3.  제출하기 클릭시 API POST통신

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 설문조사의 답변형태를 컴포넌트로 나누어 질문 type에 따라 답변 형태가 바뀌게 하기 위해 어떤 식으로 데이터를 구성하는게 좋을지 상수데이터의 기초를 잡는 부분을 많이 고민하였다.
- input의 type 이 `radio`, `checkbox`, `option`, `text` 로 다양했기 때문에 답변의 값을 얻는 부분의 로직을 생각하는게 어려웠다.
- react-select 라이브러리를 사용하여, 데이터를 어떻게 적용하고, style을 어떻게 커스터마이징 하는 부분을 배웠다. 특히, css 스타일 커스터마이징은 함수나, 프롭스를 사용하는 2가지 방법이 있어서 사용을 했지만, 하나로 줄이는 방법이 어려웠다. 추가적으로 리팩토링시에는 깔끔하게 방법을 통일 시키고 싶다.

<br />

## :: 기타 질문 및 특이 사항
- 체크를 하고 [다음]버튼을 누르고 값 체크 후 다시 [이전] 버튼을 누르면 버튼이 초기화게 되어서 이부분을 해결하는게 조금 어렵습니다.

2021-12-21 06:09 UTC, younuk23 requested changes
유진님!!
페이지 안에서 설문기록 유지하면서 화면 바꾸는 기능 어려웠을텐데 잘 도전하셔서 진행하신 것 같네요! 👍 
코멘트 드린 사항 읽어보시고 반영해주시면 됩니다!! 
PR 본문에 있는 질문은 코드상에서는 잘 파악이 되지 않아서 해결이 되지 않았다면 라운지타임에 질문주세요!

2021-12-21 06:09 UTC, younuk23 commented on src/pages/Survey/Question/SingleQuestion.js
> +                  singleValue.surveyCategory === id + 1 ? true : false
```suggestion
                  singleValue.surveyCategory === id + 1
```
이미 === 평가식 자체가 true or false로 평가되기 때문에 굳이 삼항연산자 쓸 필요 없습니다!

2021-12-21 06:09 UTC, younuk23 commented on src/pages/Survey/Survey.js
> +          {(() => {
switch 구문 잘 사용해주셨네요!!
잘 사용하셨고 다만 JSX 안에 이렇게 긴 구문이 있으니까 가독성상 좋지 않아서 별도 함수로 분리해서 함수 호출하는식으로 변경되도 좋아보입니다!! 

아니면 객체로 표현해도 좋고요!! 객체로 표현하는 것 관련해서는 내일 라이브코드리뷰때 한번 다뤄볼게요!

2021-12-21 12:43 UTC, sodalite1204 commented on src/pages/Survey/Question/SingleQuestion.js
> +                  singleValue.surveyCategory === id + 1 ? true : false
여러가지로 시도 해 봤는데 이부분이 잘 해결이 되지 않습니다.. 클릭한 후에 다음 페이지로 가면, 그 클릭했던 위치에 동일하게 체크가 되는 현상이 생깁니다. 라이브 코드 리뷰시에 봐 주시면 감사하겠습니다.

2021-12-21 12:44 UTC, sodalite1204 commented on src/pages/Survey/Survey.js
> +          {(() => {
넵 ! 객체로 표현하는 방법이 궁금합니다! 라이브리뷰 때 부탁드리겠습니다^^

2021-12-22 09:25 UTC, younuk23 approved these changes

2021-12-22 09:25 UTC, merged