[27기 구유진] nav바 레이아웃 구현
wecode-bootcamp-korea/27-2nd-SUULGO-frontend pull request #2
Opened 2021-12-14 11:38 UTC by sodalite1204

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 상단바에 sticky적용
- 카카오 소셜 로그인 (회원가입 포함) 구현
- 로그인 로그아웃
- 소셜로그인시 데이터 불러와 유저 프로필, 유저네임 나타내기
<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 기본 레이아웃 구현 (sticky를 적용하여 상단바를 고정시켰다.)
2.  styled-components 라이브러리를 사용하여 스타일을 구현
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 목데이터를 이용하여, 로그인/ 로그아웃시의 레이아웃 변경 부분을 생각하여 틀을 잡았다.
- 첫 작성부터 styled-components를 사용하여 CSS를 구현하면서 틀을 잡았다.
<br />

## :: 기타 질문 및 특이 사항
- 소셜 로그인이 너무 어렵습니다.

2021-12-15 05:41 UTC, younuk23 commented on public/index.html
> +      Kakao.init('476e7fd327b9d356e18d3d5ac07c4d01');
- 이런 외부 API key들을 그대로 코드상에 노출하면 보안에 위협이 될 수 있습니다.
- 이런 코드상에 유출되면 안되는 정보들은 환경변수를 통해서 관리해주는게 좋습니다
- CRA는 .env 파일을 통해서 편하게 환경변수를 설정할 수 있습니다.
- `.env`파일을 통해서 환경변수 관리해주시고 gitignore에 `.env` 파일을 등록해서 github상에 노출되지 않도록 해주세요
- 참고자료
- [Create React App 공식문서](https://create-react-app.dev/docs/adding-custom-environment-variables/#adding-development-environment-variables-in-env)

2021-12-15 05:41 UTC, younuk23 commented on src/components/Nav/AfterLogin/AfterLogin.js
> +const AfterContainer = styled.div`
nav에 관련된 내용이라면 div 보다 적합한 태그가 있어보입니다! 시맨틱 태그 항상 고민하고 적용해보는 연습이 중요합니다!

2021-12-15 05:41 UTC, younuk23 commented on src/components/Nav/AfterLogin/AfterLogin.js
> +  align-items: center;
만들어두신 mixin 머지됬으니까 적용해보세요!

2021-12-15 05:41 UTC, younuk23 commented on src/components/Nav/BeforeLogin/BeforeLogin.js
> +  //     .then(data => console.log(data));
유진님 1차때 라이브리뷰 때 말씀드렸다시피 코드를 주석처리하는 것은 좋지 않습니다!

2021-12-15 05:45 UTC, younuk23 requested changes
고생하셨습니다 유진님 리뷰 반영 해주세요~!

2021-12-15 05:45 UTC, younuk23 commented on src/components/Nav/BeforeLogin/BeforeLogin.js
> +  //     .then(data => console.log(data));
불필요한 주석은 삭제해주세요!
코드가 주석처리된 채로 남아있다면 필요한 상황에 제대로 사용되거나 삭제되는 일은 거의 없고 결국 계속 남아있게 됩니다.
그러다보면 이제 작성한 사람이 아닌 다른 개발자는 필요한 코드라서 주석처리한게 아닐까? 라는 생각으로 지우지 못하고
결국 그 누구도 왜 있는지는 모르면서 계속 남아있는 불필요한 레거시가 되어버립니다! 
따라서 반드시 필요한 경우가 아니면 코드를 주석처리하기보다는 삭제해주시고 만약 다시 보고싶다면 커밋 이력에 잘 남겨뒀다가 원하는 시점에 다시 보면 됩니다!

2021-12-15 05:45 UTC, younuk23 commented on src/components/Nav/BeforeLogin/BeforeLogin.js
> +  //     .then(data => console.log(data));
위 내용 참고하셔서 수정해주세요!!

2021-12-15 05:45 UTC, younuk23 commented on src/components/Nav/BeforeLogin/BeforeLogin.js
> +    <LoginButton as="a" href="loginWithKakao()">
이부분도 a tag, href 속성을 이용하는것 보다 좋은 방향이 있을 것 같네요 시도해보세요!

2021-12-15 05:45 UTC, younuk23 commented on src/components/Nav/Nav.js
> +`;
다른 문맥들끼리는 공백을 통해서 가독성에 신경써주세요

스타일드 컴포넌트도 각 컴포넌트별로 한 줄 공백 주는게 좋습니다!

2021-12-15 05:45 UTC, younuk23 commented on src/components/Nav/Nav.js
> +  z-index: 1000;
- CSS 속성은 레이아웃에 영향을 많이 주는 순서대로, 인접 속성끼리 묶어서 
작성해주는게 좋습니다. 
- 일전에 안내해드린 [css 속성순서 컨벤션](https://www.notion.so/wecode/Westagram-JS-Refactoring-Checklist-dcff20de07b6449d89d82980e7af9cba#12ef362870c54d928ad6f56dab0b4b0e) 확인하시고 지켜서 작성해주세요

2021-12-15 05:45 UTC, younuk23 commented on src/components/Nav/Nav.js
> +  position: sticky;
👍 
sticky 1차때 많이 고생하면서 찾아보고 적용해본 경험 있으니까 다음에 할때는 그때 경험 기반으로 금방 이해하고 적용할 수 있지 않나요?? :)

그때처럼 지금은 소셜 로그인 많이 어려우셔도 여기서 많이 찾아보고 고민해보고 적용해본 경험이 나중에 실력이 될겁니다 화이팅  💪

2021-12-15 08:13 UTC, sodalite1204 commented on public/index.html
> +      Kakao.init('476e7fd327b9d356e18d3d5ac07c4d01');
넵!! 잘 적용해서 PR하겠습니다!

2021-12-15 08:14 UTC, sodalite1204 commented on src/components/Nav/AfterLogin/AfterLogin.js
> +const AfterContainer = styled.div`
nav태그로 변경 적용하였습니다! styled-components사용시에도 주의해서 코드 작성하도록 하겠습니다.

2021-12-15 08:14 UTC, sodalite1204 commented on src/components/Nav/AfterLogin/AfterLogin.js
> +  align-items: center;
네! pull 댕겨서 mixin적용하였습니다🙂

2021-12-15 08:56 UTC, sodalite1204 commented on src/components/Nav/BeforeLogin/BeforeLogin.js
> +  //     .then(data => console.log(data));
연욱님 감사합니다. 불필요한 주석은 만들지 않고 PR올리는 습관을 기르도록 하겠습니다!

2021-12-15 08:57 UTC, sodalite1204 commented on src/components/Nav/BeforeLogin/BeforeLogin.js
> +    <LoginButton as="a" href="loginWithKakao()">
이 부분은 onClick이벤트로 함수가 실행되도록 수정하였습니다!

2021-12-15 08:58 UTC, sodalite1204 commented on src/components/Nav/Nav.js
> +`;
스타일드 컴포넌트도 한 줄 공백 유의하겠습니다!

2021-12-15 09:03 UTC, sodalite1204 commented on src/components/Nav/Nav.js
> +  z-index: 1000;
레이아웃 영향을 많이 주는 순서대로, 인접 속성끼리 작성하도록 유의하겠습니다.

2021-12-15 09:05 UTC, sodalite1204 commented on src/components/Nav/Nav.js
> +  position: sticky;
연욱님 감사합니다! 소셜 로그인 너무 힘들었는데 다시 힘내서 퐈이팅 할 수 있을 것 같아요! 공식문서도 많이 찾아보고 할 수 있는 최선을 다해서 해 보도록 노력하겠습니다! 많이 도와주세요 ☺️✨

2021-12-16 02:30 UTC, younuk23 requested changes
리뷰 몇가지 마이너한 사항 있습니다 확인 하시고 반영해주세요!

2021-12-16 02:30 UTC, younuk23 commented on src/components/Nav/AfterLogin/AfterLogin.js
> +  color: ${props => props.theme.mint};
```suggestion
  color: ${({theme}) => theme.mint};
```
다른 함수와 마찬가지로 매개변수 자리에서 구조분해할당 가능합니다!

2021-12-16 02:30 UTC, younuk23 commented on src/components/Nav/BeforeLogin/BeforeLogin.js
> +    });
👍

2021-12-16 02:30 UTC, younuk23 commented on src/components/Nav/Nav.js
> +  position: sticky;
👍

2021-12-16 05:18 UTC, sodalite1204 commented on src/components/Nav/AfterLogin/AfterLogin.js
> +  color: ${props => props.theme.mint};
넵! 구조 분해 할당이 가능하다는 점 알려주셔서 감사합니다! 보다 간결하게 사용할 수 있어서 좋아요! 바로 적용 시켰습니다!!🙂

2021-12-16 05:18 UTC, sodalite1204 commented on src/components/Nav/BeforeLogin/BeforeLogin.js
> +    });
감사합니다! 🥰

2021-12-17 02:20 UTC, younuk23 reviewed
고생하셨습니다 유진님! 코드는 제가 라운지타임에 한번 봐드린 내용인 것 같아서 현재 상태에서 코멘트로 리뷰드릴 부분은 크게 없는 것 같고 제가 라운지에서 가이드 드린 부분 수정해서 push 해주세요!

2021-12-17 02:21 UTC, younuk23 commented
사이더 코멘트도 해결해주세요!!

2021-12-17 03:18 UTC, younuk23 approved these changes
LGTM 👍 
코멘트 드린 부분은 확인해보시고 나중에 더 추가해보세요 소셜로그인 성공 👍

2021-12-17 03:18 UTC, younuk23 commented on src/components/Nav/AfterLogin/AfterLogin.js
> +    localStorage.removeItem('token');
이부분은 나중에 백엔드에 로그아웃 요청까지 깔끔하게 보내는걸로 추후에 더 기능 추가해보세요!!

2021-12-17 03:18 UTC, merged