[27기 오동녘어진이] detail page layout
wecode-bootcamp-korea/27-2nd-SUULGO-frontend pull request #4
Opened 2021-12-14 14:58 UTC by eojine94

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표
- 상세페이지 레이아웃 잡기.
- 서버에서 user info 불러와서 정상적으로 렌더링하기.
- 약속잡기 기능, user에 대한 리뷰달기 기능 구현.

<br />

## :: 구현 사항 설명
1. 상세 페이지 레이아웃 잡기.

<br />

## :: 성장 포인트
- position: sticky에 대해서 공부함.

<br />

## :: 기타 질문 및 특이 사항
-

2021-12-15 05:50 UTC, younuk23 requested changes
컨플릭 발생한 부분 해결 및 리뷰 반영해주세요 어진님 :)
그리고 구현목표로 잡으신 부분이 내용이 다소 한 브랜치에서 담기에는 방대해보여서 분리하시는 것을 권장드립니다!

2021-12-15 05:50 UTC, younuk23 commented on src/pages/Detail/Detail.js
> +    }
styled components 선언부가 함수형 컴포넌트 안에 있을 필요는 없습니다! 다른 팀원분 코드 참고하셔서 함수 컴포넌트 아래 부분으로 선언부분 이동해주세요!!
지금은 가독성에도 좋지않고 매 렌더링마다 스타일드 컴포넌트 선언이 이루어져서 불필요한 연산이 발생하고 있네요!!

2021-12-15 05:50 UTC, younuk23 commented on src/pages/Detail/Detail.js
> +              <div className="matchTagCategoryName">술 종류</div>
여기서부터 유사한 부분이 계속 반복되는 것 같네요!
이런 부분같은경우에는 고정되어있다면 상수데이터 + Array.map 메소드 이용해서 표현하는 것이 훨씬 간결하고 유지보수에도 용이합니다!

2021-12-15 05:50 UTC, younuk23 commented on src/pages/Detail/Detail.js
> +              <div className="matchTagCategoryName">술 종류</div>
infoWrapper 등 다른 부분도 유사한 파트가 많이 보여서 한번 고민해보시고 적용해보세요!

2021-12-15 05:50 UTC, younuk23 commented on src/pages/Detail/Detail.js
> +        {/* 왼 */}
제 생각에는 불필요한 주석 같습니다!

2021-12-15 05:50 UTC, younuk23 commented on src/pages/Detail/Detail.js
> +          <section className="profileOverview">
- styled-component를 이용해서 스타일링이 된 태그들은 해당 definition으로 이동해서 바로 스타일링을 확인이 가능한데 className으로 선언한 부분은 바로 definition으로 이동이 불가능해서 스타일링 파악하기에 어려움이 있음
- 위의 내용에 덧붙여서 className을 이용한 스타일링의 nesting depth가 깊어지는 경우에는 더 더욱 찾기가 힘들어짐
- depth가 깊어지는 경우 뿐만 아니라 1depth로도 className을 이용한 스타일 선언부가 길어지는 경우에도 해당 스타일링을 찾기 어려워짐
- 위의 사항들로 인해서 CSS in JS(styled-components 등)을 이용한 스타일링을 하는 경우에는 라이브러리 사용상 강제되는 등의 불가피한 부분을 제외하고는 className을 통한 스타일링은 최대한 지양하는게 권장됩니다.

2021-12-15 05:50 UTC, younuk23 commented on src/pages/Detail/Detail.js
> +          <section className="profileOverview">
위의 이유들로 인해서 스타일드 컴포넌트 사용하면 className은 사용할 필요 없습니다!! 스타일이 필요한 경우에는 스타일드컴포넌트로 선언해서 사용해주세요!

2021-12-16 02:34 UTC, younuk23 requested changes
고생하셨습니다 어진님!
.env 부분만 해결해주세요!
그리고 코멘트 달아드린 것 resolve 보다 답글 달거나 이모지 다는걸로 리액션주세요! resolve 하면 제가 다시 확인하기가 어려워서 제가 보고 resolve 할게요!!

2021-12-16 02:34 UTC, younuk23 commented on src/.env
> +REACT_APP_JAVASCRIPT_KEY=476e7fd327b9d356e18d3d5ac07c4d01
git에 있어선 안되는 파일이 올라와 있네요!!
유진님한테 가이드 드린 부분이라 확인하시고 git상에서 없애주세요!
한번 올라온 파일은 gitignore에 등록해도 캐쉬가 남아있어서 계속 유지되기 때문에 캐쉬 지우는 방법도 찾아보고 적용해보세요!

2021-12-16 02:34 UTC, younuk23 commented on src/pages/Detail/Detail.js
> +    tagRef.current?.scrollIntoView({ behavior: 'smooth' });
👍

2021-12-16 05:16 UTC, eojine94 commented on src/.env
> +REACT_APP_JAVASCRIPT_KEY=476e7fd327b9d356e18d3d5ac07c4d01
캐쉬 삭제완료해서 업로드했습니다 !

2021-12-16 09:24 UTC, younuk23 commented
컨플릭 해결해주세요!

2021-12-16 09:44 UTC, younuk23 commented
어진님 브랜치 합칠 때 머지로 합치면 안됩니다! 리베이스로 합쳐주세요!!

2021-12-16 09:57 UTC, younuk23 commented
Good 커밋 메세지는 지금처럼 conflict 해결 이라고 단순하게 남기는 게 아니라 이 브랜치에서 모든 작업을 하나의 커밋메세지로 표현하는 만큼 핵심 작업 주제 및 내용이 잘 드러나게 작성해주세요!!
위 사항은 다음부터 적용해주세요!! 커밋 메시지로 소통하고 이력을 잘 남기는것도 중요한 역량입니다!

2021-12-16 09:57 UTC, merged