[27기 김재호]ADD : 메인리스트페이지 레이아웃완료
wecode-bootcamp-korea/27-2nd-SUULGO-frontend pull request #7
Opened 2021-12-16 08:08 UTC by wogh09

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 각자의 설정된 아이콘을 클릭하면 거기에 맞는 데이터를 뽑아서 구현해주는게 목표입니다
<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 스타일 컴포넌트로 이모티콘을 구현하였습니다.
2. map함수를 이용해 정해진 개수에 맞게 보여지게 만들었습니다

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 맵함수나 패치함수를 쓰며 목데이터를 사용해 한단계 성장하였습니다
<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.

2021-12-16 09:43 UTC, younuk23 requested changes
고생하셨습니다 재호님 리뷰 확인 및 반영해주세요!

2021-12-16 09:43 UTC, younuk23 commented on .env
> +REACT_APP_JAVASCRIPT_KEY=476e7fd327b9d356e18d3d5ac07c4d01
이 정보들은 깃헙상에 유출되면 안되는 정보입니다!
gitignore에 등록해서 깃으로 관리 안되도록 해주세요

- .gitignore에 등록하기 전에 한번이라도 git으로 관리해버린 파일들은(add, commit 등) 계속해서 git에 의해서 추적이 됩니다.
- 이를 없애기 위해서는 git의 기존 캐쉬를 삭제해줘야합니다.
- 아래의 명령어를 통해 캐쉬 삭제해주시고 git으로 추적 안되는 것 확인해주세요
- `git rm --cached 파일이름`

2021-12-16 09:43 UTC, younuk23 commented on src/pages/List/List.js
> +    fetch('http://localhost:3002/data/mockdata.json', {
localhost:3002는 생략가능합니다! 생략하고 절대경로 시작하게 되면 자연스럽게 현재 프로젝트가 실행되고 있는 URL로 인식이 됩니다.
오히려 기입하게 되면 localhost:3002가 아닌 다른 URL에서 프로젝트가 실행될 때 에러가 발생할 수 있습니다

2021-12-16 09:43 UTC, younuk23 commented on src/pages/List/List.js
> +  return (
다른 문맥들끼리는 공백을 통해서 가독성에 신경써주세요
위의 로직들과 return문은 다른 문맥이니까 공백 부여해주세요

2021-12-16 09:43 UTC, younuk23 commented on src/pages/List/List.js
> +          <ListImage src="/images/스인.jpg" />
alt attribute 부여해주세요!

2021-12-16 09:43 UTC, younuk23 commented on src/pages/List/List.js
> +            {memberList.map(babo => {
babo?

2021-12-16 09:43 UTC, younuk23 commented on src/pages/List/List.js
> +                  alcohol_category={babo.id}
camelCase로 이름 지어주세요!

2021-12-16 09:43 UTC, younuk23 commented on src/pages/List/List.js
> +const ListMain = styled.div``;
스타일 부여 안할 거면은 굳이 스타일드 컴포넌트로 만들 필요 없이 태그 그대로 사용하면 됩니다!

2021-12-16 09:43 UTC, younuk23 commented on src/pages/List/List.js
> +  height: 100%;
- 레이아웃 구현시, '부모의 크기가 고정인 경우'와 '자식의 크기만큼 늘어나는 경우'를 구분해주세요.
- 부모의 height가 자식 요소의 높이만큼 늘어나게 하려면 부모에 고정값을 부여하면 안 됩니다.
- 레이아웃을 결정하실 때 부모요소에 큰 고정폭은 가급적 사용하지 않습니다. 자식요소의 너비를 누적하여 부모 요소가 결정될 수 있도록 해주세요.
- 가급적 고정 가로, 세로의 사용을 피하고, 꼭 필요한 경우가 아니라면 부모 요소의 크기는 자식 요소 + margin, padding을 통해 자연히 결정될 수 있도록 해주세요.
- 여기서 꼭 필요한 경우란, flex 처럼 부모의 고정값에 따라 자식 요소가 배치되는 경우 등이 예시가 될 수 있겠습니다.
- 즉, 모든 요소에 무조건 고정값을 사용하기보다는 유연성을 고려해 상황에 따라 적절히 고정값을 이용하는 것이 좋겠습니다.
- 2주차에 제공해드린 [위스타그램 리팩토링 체크리스트](https://www.notion.so/wecode/Westagram-JS-Refactoring-Checklist-dcff20de07b6449d89d82980e7af9cba#fffc19a72f6d41c3bcdded99c8667bed)에 해당 내용 있으니 참고해보세요

2021-12-16 12:57 UTC, wogh09 commented on src/pages/List/List.js
> +    fetch('http://localhost:3002/data/mockdata.json', {
수정하였습니다

2021-12-16 12:57 UTC, wogh09 commented on src/pages/List/List.js
> +  return (
수정하였습니다!!

2021-12-16 13:09 UTC, wogh09 commented on src/pages/List/List.js
> +          <ListImage src="/images/스인.jpg" />
수정하였습니다

2021-12-16 13:10 UTC, wogh09 commented on src/pages/List/List.js
> +            {memberList.map(babo => {
맵데이터 써본다고 아무이름막지었는데 깜빡하고 다시 수정못했습니다 ㅠㅠ 수정했습니다!

2021-12-16 13:10 UTC, wogh09 commented on src/pages/List/List.js
> +                  alcohol_category={babo.id}
수정했습니다

2021-12-16 13:11 UTC, wogh09 commented on src/pages/List/List.js
> +  height: 100%;
수정했습니다!!!!

2021-12-16 13:34 UTC, wogh09 commented on src/pages/List/List.js
> +const ListMain = styled.div``;
넵 수정했습니다!!

2021-12-16 14:08 UTC, wogh09 commented on .env
> +REACT_APP_JAVASCRIPT_KEY=476e7fd327b9d356e18d3d5ac07c4d01
수정했습니다

2021-12-17 03:07 UTC, younuk23 reviewed
Good 👍 
리뷰드린 사항 반영해주세요!

2021-12-17 03:07 UTC, younuk23 commented on src/pages/List/Icon.js
> +export default Icon;
재호님 제가 살짝 코드상에서 헷갈려서 그런데 올리신 mainpage PR에 있는 내용과 동일한 부분인가요?
유사한 부분이 보여서 질문드립니다. 만약 동일한 파트라면 하나의 컴포넌트로 재사용해주시면 될 것 같네요!

2021-12-17 03:07 UTC, younuk23 commented on src/pages/List/List.js
> +    fetch('data/mockdata.json', {
절대경로로 적어주세요! 상대경로로 지정하게 되면 path의 depth가 깊어졌을때 원하는대로 public 폴더에 접근을 하지 못합니다!

예시) 상대경로로 작성했을 시
- http://localhost:3000/main => 이경우에는 상대경로로 작성해도 public 폴더로 정상 인식해서 정상동작
- http://localhost:3000/detail/1 => 이경우에는 path의 depth가 깊어져서 상대경로로 지정하게되면 pubilc/detail 폴더안에서 찾으려고 하기 때문에 제대로 동작하지 않음.

2021-12-17 03:07 UTC, younuk23 commented on src/pages/List/List.js
> +    fetch('data/mockdata.json', {
```suggestion
    fetch('/data/mockdata.json', {
```

2021-12-20 02:17 UTC, younuk23 commented
재호님! 리뷰 드린 PR 두개 다 반영이 안되있네요!
리뷰 반영을 최우선적으로 작업 진행해주세요!!

2021-12-21 05:13 UTC, wogh09 commented on src/pages/List/List.js
> +    fetch('data/mockdata.json', {
수정하였습니다

2021-12-21 05:13 UTC, wogh09 commented on src/pages/List/Icon.js
> +export default Icon;
수정하였습니다

2021-12-22 01:26 UTC, younuk23 approved these changes
재호님 추가기능 구현중이신가요? 이 브랜치는 여기서 마무리해도 될 것 같은데요!

2021-12-22 06:27 UTC, merged